create table "ROOT".ADMIN
(
	ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
	LOGIN VARCHAR(40),
	PASSWORD VARCHAR(8)
);
create table "ROOT".USERS
(
	ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
	NAME VARCHAR(40)
);

create table "ROOT".CONTACTS
(
	ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
	USER_ID INTEGER not null,
	NAME VARCHAR(40),
	PHONE VARCHAR(20),
	CELLPHONE VARCHAR(20),
	
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

create table "ROOT".PUBLICCONTACTS
(
	ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) not null primary key,
	NAME VARCHAR(40),
	PHONE VARCHAR(20),
	CELLPHONE VARCHAR(20)
);