/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditUserForm.java
 *
 * Created on 09/05/2012, 01:24:53
 */
package presentation.desktop;

import business.BusinessException;
import business.BusinessFactory;
import business.spec.IContact;
import business.spec.IPublicContacts;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author luciano
 */
public class PublicImportContactForm extends javax.swing.JDialog {
    
    private IPublicContacts contact = BusinessFactory.getInstance().getPublicContact();
    /** Creates new form EditUserForm */
    public PublicImportContactForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        txtCSV = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(presentation.desktop.MeucciApp.class).getContext().getResourceMap(PublicImportContactForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle"); // NOI18N
        jLabel3.setText(bundle.getString("ImportContactForm.lblTitle.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        lblPath.setText(bundle.getString("ImportContactForm.lblPath.text")); // NOI18N
        lblPath.setName("lblPath"); // NOI18N

        txtCSV.setText(resourceMap.getString("txtCSV.text")); // NOI18N
        txtCSV.setName("txtCSV"); // NOI18N

        btnFind.setMnemonic(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("mnFind.text").charAt(0));
        btnFind.setText(bundle.getString("btnFind.text")); // NOI18N
        btnFind.setName("btnFind"); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnImport.setMnemonic(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("mnImport.text").charAt(0));
        btnImport.setText(bundle.getString("btnImport.text")); // NOI18N
        btnImport.setName("btnImport"); // NOI18N
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblPath))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPath)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(21, 21, 21)
                .addComponent(btnImport)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-204)/2, 474, 204);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        JFileChooser fc = new JFileChooser();
        // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter((java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILES")), java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV"));
        
        fc.setFileFilter(filter);
        
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File csvDirectory = fc.getSelectedFile();
            txtCSV.setText(csvDirectory.getPath());
        } else {
            JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILE NOT SELECTED! PLEASE, SELECT A CSV FILE."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ALERT"),
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        try {
            if(txtCSV.getText().isEmpty())
                JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILE NOT SELECTED! PLEASE, SELECT A CSV FILE."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ALERT"),
                    JOptionPane.WARNING_MESSAGE);
            else if(contact.importContacts(txtCSV.getText())){
                JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CONTACTS IMPORTED SUCCESSFULLY!"),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI INFORMATION"),
                    JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    Menu.getInstance().updateDataFormView();
            }else
                JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CONTACTS NOT IMPORTED."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ERROR"),
                    JOptionPane.INFORMATION_MESSAGE);
            
        } catch (BusinessException ex) {
            Logger.getLogger(PublicImportContactForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnImport;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPath;
    private javax.swing.JTextField txtCSV;
    // End of variables declaration//GEN-END:variables



   
}
