/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Report.java
 *
 * Created on 17/06/2012, 13:21:47
 */
package presentation.desktop;

import business.BusinessException;
import business.BusinessFactory;
import business.spec.IFatura;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.Configuration;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luciano
 */
public class Report extends javax.swing.JDialog {
    private static Report instance;
    private IFatura fatura = BusinessFactory.getInstance().getFatura();

    /** Creates new form Report */
    private Report(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }
    
    public static Report getInstance() {
        if (instance == null) {
            instance = new Report(null);
        }
        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCSVDirectory = new javax.swing.JButton();
        txtCSV = new javax.swing.JTextField();
        lblCSV = new javax.swing.JLabel();
        txtReport = new javax.swing.JTextField();
        btnReportsDirectory = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        btnGenerateReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("frmReport"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(presentation.desktop.MeucciApp.class).getContext().getResourceMap(Report.class);
        lblTitle.setFont(resourceMap.getFont("lblTitle.font")); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle"); // NOI18N
        lblTitle.setText(bundle.getString("ReportsForm.lblTitle.text")); // NOI18N
        lblTitle.setName("lblTitle"); // NOI18N

        btnCSVDirectory.setMnemonic(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("mnFind.text").charAt(0));
        btnCSVDirectory.setText(bundle.getString("btnFind.text")); // NOI18N
        btnCSVDirectory.setName("btnCSVDirectory"); // NOI18N
        btnCSVDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVDirectoryActionPerformed(evt);
            }
        });

        txtCSV.setText(resourceMap.getString("txtCSV.text")); // NOI18N
        txtCSV.setName("txtCSV"); // NOI18N

        lblCSV.setText(bundle.getString("ReportsForm.lblCSV.text")); // NOI18N
        lblCSV.setName("lblCSV"); // NOI18N

        txtReport.setName("txtReport"); // NOI18N

        btnReportsDirectory.setMnemonic(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("mnFind2.text").charAt(0));
        btnReportsDirectory.setText(bundle.getString("btnFind.text")); // NOI18N
        btnReportsDirectory.setName("btnReportsDirectory"); // NOI18N
        btnReportsDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsDirectoryActionPerformed(evt);
            }
        });

        lblReport.setText(bundle.getString("ReportsForm.lblReport.text")); // NOI18N
        lblReport.setName("lblReport"); // NOI18N

        btnGenerateReports.setMnemonic(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("mnGenerate.text").charAt(0));
        btnGenerateReports.setText(bundle.getString("btnGenerate.text")); // NOI18N
        btnGenerateReports.setName("btnGenerateReports"); // NOI18N
        btnGenerateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCSVDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblReport)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnReportsDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblCSV, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnGenerateReports, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCSVDirectory, btnReportsDirectory});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCSVDirectory))
                .addGap(24, 24, 24)
                .addComponent(lblReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportsDirectory))
                .addGap(53, 53, 53)
                .addComponent(btnGenerateReports)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-469)/2, (screenSize.height-409)/2, 469, 409);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCSVDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVDirectoryActionPerformed
        JFileChooser fc = new JFileChooser();
        // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter((java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILES")), java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV"));
        
        fc.setFileFilter(filter);
        
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File csvDirectory = fc.getSelectedFile();
            txtCSV.setText(csvDirectory.getPath());
            //JOptionPane.showMessageDialog(null, "Voce escolheu o diretório: " + csvDirectory.getName());
        } else {
            JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILE NOT SELECTED! PLEASE, SELECT A CSV FILE."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ALERT"),
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnCSVDirectoryActionPerformed

    private void btnReportsDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsDirectoryActionPerformed
        JFileChooser fc = new JFileChooser();
        // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File reportDirectory = fc.getSelectedFile();
            txtReport.setText(reportDirectory.getPath());
            //JOptionPane.showMessageDialog(null, "Voce escolheu o diretório: " + csvDirectory.getName());
        } else {
            JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("DIRECOTORY TO SAVE REPORTS NOT SELECTED! PLEASE, SELECT A DIRECOTORY."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ALERT"),
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnReportsDirectoryActionPerformed

    private void btnGenerateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportsActionPerformed
        String header = Configuration.getInstance().getProperty(java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("HEADER_DISCARD"));
        if(txtCSV.getText().isEmpty() || txtReport.getText().isEmpty())
            JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("CSV FILE OR DIRECOTORY TO SAVE REPORTS NOT SELECTED!"),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ALERT"),
                    JOptionPane.WARNING_MESSAGE);
        else{
            try {
                if(fatura.calculate(fatura.importFat(txtCSV.getText(), Integer.parseInt(header)), txtReport.getText()))
                    JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("REPORTS GENERATED SUCCESSFULLY!"),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI INFORMATION"),
                    JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("REPORTS NOT GENERATED."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ERROR"),
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (BusinessException ex) {
                JOptionPane.showMessageDialog(this,
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("AN ERROR OCURRED DURING GENERATING REPORTS."),
                    java.util.ResourceBundle.getBundle("presentation/desktop/languages/Bundle").getString("MEUCCI ERROR"),
                    JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnGenerateReportsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSVDirectory;
    private javax.swing.JButton btnGenerateReports;
    private javax.swing.JButton btnReportsDirectory;
    private javax.swing.JLabel lblCSV;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCSV;
    private javax.swing.JTextField txtReport;
    // End of variables declaration//GEN-END:variables
}
